[GLOBAL]
pants_version = "$PANTS_VERSION"
backend_packages = [
  "pants.backend.docker",
  "pants.backend.docker.lint.hadolint"
]

[anonymous-telemetry]
enabled = false

[docker]
build_verbose = true
