apiVersion: v1
kind: Pod

metadata:
  name: sonarqube

spec:
  volumes:
    - name: code
      hostPath:
        path: apps/payments/src
  containers:
    - name: main
      image: sonarqube:9.9.0-community
      volumeMounts:
        - mountPath: /usr/code
          name: code
      resources:
        requests:
          memory: 256Mi
          cpu: 0.5m
        limits:
          memory: 1Gi
          cpu: 1m