plugin_repo(
  name = "please_reuse",
  revision = "v0.1.0",
  plugin = "please-reuse",
  owner = "mrsauravsahu",
)

plugin_repo(
  name = "shell",
  revision = "v0.2.0",
  plugin = "shell-rules",
  owner = "please-build",
)

plugin_repo(
  name = "docker",
  revision = "v0.1.0",
  plugin = "docker-rules",
  owner = "please-build",
)
