// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using payobills.bills.data;

#nullable disable

namespace payobills.bills.data.migrations
{
    [DbContext(typeof(BillsContext))]
    partial class BillsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");
#pragma warning restore 612, 618
        }
    }
}
