import os
import requests

NOCODB_URL = "http://localhost:8081"
API_KEY = os.environ["NOCODB_API_KEY"]
BASE_ID = os.environ["NOCODB_BASE_ID"]
TABLE_ID = os.environ["NOCODB_TABLE_ID"]

NOTES = {
    "AED": "Official currency of the UAE, pegged to the USD since 1997.",
    "AFN": "Currency of Afghanistan, introduced in 2002 replacing the old afghani.",
    "ALL": "Albanian lek, named after Alexander the Great ('Leka' in Albanian).",
    "AMD": "Armenian dram, reintroduced in 1993 after the Soviet-era ruble.",
    "ANG": "Used in Curaçao and Sint Maarten, will be replaced by the Caribbean guilder.",
    "AOA": "Angolan kwanza, named after the Kwanza river.",
    "ARS": "Argentine peso, has experienced significant inflation over recent decades.",
    "AUD": "Australian dollar, also used in several Pacific island nations.",
    "AWG": "Aruban florin, pegged to the USD at 1.79 florin per dollar.",
    "AZN": "Azerbaijani manat, introduced in 2006 replacing the old manat.",
    "BAM": "Bosnian convertible mark, pegged to the euro since its introduction in 1995.",
    "BBD": "Barbadian dollar, pegged to the USD at 2:1.",
    "BDT": "Bangladeshi taka, the word 'taka' is also the Bengali word for money.",
    "BGN": "Bulgarian lev, pegged to the euro at 1.95583 lev per euro.",
    "BHD": "Bahraini dinar, one of the highest-valued currency units in the world.",
    "BIF": "Burundian franc, one of the lowest-valued currency units in the world.",
    "BMD": "Bermudian dollar, pegged 1:1 to the USD.",
    "BND": "Brunei dollar, interchangeable at par with the Singapore dollar.",
    "BOB": "Boliviano, named after Simón Bolívar, the South American liberator.",
    "BRL": "Brazilian real, introduced in 1994 as part of the Plano Real to curb hyperinflation.",
    "BSD": "Bahamian dollar, pegged 1:1 to the USD.",
    "BTN": "Bhutanese ngultrum, pegged at par with the Indian rupee.",
    "BWP": "Botswana pula, meaning 'rain' in Setswana — a symbol of good fortune.",
    "BYN": "Belarusian ruble, redenominated in 2016 (1 new = 10,000 old).",
    "BZD": "Belize dollar, pegged to the USD at 2:1.",
    "CAD": "Canadian dollar, one of the world's major reserve currencies.",
    "CDF": "Congolese franc, currency of the Democratic Republic of Congo.",
    "CHF": "Swiss franc, considered a safe-haven currency globally.",
    "CLP": "Chilean peso, Chile is a major copper exporter influencing its value.",
    "CNY": "Chinese yuan renminbi, the world's most traded emerging-market currency.",
    "COP": "Colombian peso, Colombia is a major coffee and oil exporter.",
    "CRC": "Costa Rican colón, named after Christopher Columbus ('Colón' in Spanish).",
    "CUP": "Cuban peso, used alongside the Cuban convertible peso domestically.",
    "CVE": "Cape Verdean escudo, pegged to the euro via agreement with Portugal.",
    "CZK": "Czech koruna, the EU member Czech Republic has yet to adopt the euro.",
    "DJF": "Djiboutian franc, pegged to the USD since 1973.",
    "DKK": "Danish krone, Denmark uses it despite being an EU member.",
    "DOP": "Dominican peso, the Dominican Republic has one of the largest Caribbean economies.",
    "DZD": "Algerian dinar, Algeria is a major natural gas and oil exporter.",
    "EGP": "Egyptian pound, one of the oldest currencies still in use.",
    "ERN": "Eritrean nakfa, introduced in 1997 after Eritrea's independence from Ethiopia.",
    "ETB": "Ethiopian birr, 'birr' means silver in Amharic.",
    "EUR": "Euro, shared by 20 EU member states and the world's second reserve currency.",
    "FJD": "Fijian dollar, Fiji is a major Pacific island tourism destination.",
    "FKP": "Falkland Islands pound, pegged 1:1 to the British pound sterling.",
    "GBP": "British pound sterling, the world's oldest currency still in use.",
    "GEL": "Georgian lari, introduced in 1995 replacing the Soviet-era coupon.",
    "GHS": "Ghanaian cedi, redenominated in 2007 (1 new cedi = 10,000 old cedis).",
    "GIP": "Gibraltar pound, pegged 1:1 to the British pound.",
    "GMD": "Gambian dalasi, 'dalasi' derives from the five-franc coin used historically.",
    "GNF": "Guinean franc, Guinea holds some of the world's largest bauxite reserves.",
    "GTQ": "Guatemalan quetzal, named after the resplendent quetzal bird.",
    "GYD": "Guyanese dollar, Guyana has seen rapid growth from offshore oil discoveries.",
    "HKD": "Hong Kong dollar, a major financial hub currency freely convertible worldwide.",
    "HNL": "Honduran lempira, named after a 16th-century indigenous chief.",
    "HRK": "Croatian kuna, replaced by the euro in January 2023.",
    "HTG": "Haitian gourde, Haiti shares the island of Hispaniola with the Dominican Republic.",
    "HUF": "Hungarian forint, Hungary is an EU member but retains its own currency.",
    "IDR": "Indonesian rupiah, Indonesia has the largest economy in Southeast Asia.",
    "ILS": "Israeli new shekel, introduced in 1986 replacing the hyperinflated old shekel.",
    "INR": "Indian rupee, currency of the world's most populous country.",
    "IQD": "Iraqi dinar, Iraq holds some of the world's largest proven oil reserves.",
    "IRR": "Iranian rial, one of the lowest-valued currency units due to sanctions.",
    "ISK": "Icelandic króna, Iceland recovered strongly after its 2008 banking collapse.",
    "JMD": "Jamaican dollar, Jamaica is known globally for reggae music and athletics.",
    "JOD": "Jordanian dinar, one of the highest-valued currency units in the world.",
    "JPY": "Japanese yen, the world's third most traded currency and a safe-haven asset.",
    "KES": "Kenyan shilling, Kenya is East Africa's largest economy.",
    "KGS": "Kyrgyzstani som, 'som' means pure (as in pure gold) in Kyrgyz.",
    "KHR": "Cambodian riel, the USD is widely used alongside it in Cambodia.",
    "KMF": "Comorian franc, pegged to the euro via France.",
    "KPW": "North Korean won, tightly controlled and not convertible internationally.",
    "KRW": "South Korean won, South Korea is a global leader in electronics and cars.",
    "KWD": "Kuwaiti dinar, the highest-valued currency unit in the world.",
    "KYD": "Cayman Islands dollar, pegged to the USD at 1.2:1.",
    "KZT": "Kazakhstani tenge, Kazakhstan is a major oil and uranium producer.",
    "LAK": "Lao kip, Laos is a landlocked nation in Southeast Asia.",
    "LBP": "Lebanese pound, has severely depreciated amid Lebanon's ongoing financial crisis.",
    "LKR": "Sri Lankan rupee, Sri Lanka faced a major economic crisis in 2022.",
    "LRD": "Liberian dollar, Liberia was founded by freed American slaves in 1847.",
    "LSL": "Lesotho loti, pegged 1:1 to the South African rand.",
    "LYD": "Libyan dinar, Libya holds Africa's largest proven oil reserves.",
    "MAD": "Moroccan dirham, Morocco is Africa's largest phosphate exporter.",
    "MDL": "Moldovan leu, Moldova is one of Europe's smallest and poorest countries.",
    "MGA": "Malagasy ariary, one of only two non-decimal currencies in the world.",
    "MKD": "Macedonian denar, North Macedonia is a candidate EU member state.",
    "MMK": "Myanmar kyat, Myanmar has faced economic turmoil following the 2021 coup.",
    "MNT": "Mongolian tögrög, Mongolia has vast coal and copper reserves.",
    "MOP": "Macanese pataca, Macau is the world's largest gambling revenue hub.",
    "MRU": "Mauritanian ouguiya, one of only two non-decimal currencies in the world.",
    "MUR": "Mauritian rupee, Mauritius is a high-income African island economy.",
    "MVR": "Maldivian rufiyaa, the Maldives is famous for luxury tourism and coral atolls.",
    "MWK": "Malawian kwacha, Malawi is one of the world's least developed countries.",
    "MXN": "Mexican peso, the most traded Latin American currency.",
    "MYR": "Malaysian ringgit, Malaysia is a major palm oil and electronics exporter.",
    "MZN": "Mozambican metical, Mozambique has significant natural gas reserves.",
    "NAD": "Namibian dollar, pegged 1:1 to the South African rand.",
    "NGN": "Nigerian naira, Nigeria has Africa's largest economy.",
    "NIO": "Nicaraguan córdoba, named after Francisco Hernández de Córdoba.",
    "NOK": "Norwegian krone, Norway manages its oil wealth through a sovereign wealth fund.",
    "NPR": "Nepalese rupee, pegged to the Indian rupee at 1.6:1.",
    "NZD": "New Zealand dollar, also used in several Pacific island territories.",
    "OMR": "Omani rial, pegged to the USD; one of the world's highest-valued currencies.",
    "PAB": "Panamanian balboa, pegged 1:1 to the USD; USD is legal tender in Panama.",
    "PEN": "Peruvian sol, Peru is a major copper and gold producer.",
    "PGK": "Papua New Guinean kina, PNG has rich mineral and natural gas resources.",
    "PHP": "Philippine peso, the Philippines is a major source of global remittances.",
    "PKR": "Pakistani rupee, Pakistan is the world's fifth most populous country.",
    "PLN": "Polish złoty, Poland has one of the largest economies in Central Europe.",
    "PYG": "Paraguayan guaraní, Paraguay is a major soy and beef exporter.",
    "QAR": "Qatari riyal, Qatar has one of the world's highest GDPs per capita.",
    "RON": "Romanian leu, Romania is an EU member targeting euro adoption.",
    "RSD": "Serbian dinar, Serbia is a candidate EU member state.",
    "RUB": "Russian ruble, has faced significant depreciation due to sanctions.",
    "RWF": "Rwandan franc, Rwanda has one of Africa's fastest-growing economies.",
    "SAR": "Saudi riyal, pegged to the USD; Saudi Arabia is the world's top oil exporter.",
    "SBD": "Solomon Islands dollar, the Solomons are a Pacific archipelago nation.",
    "SCR": "Seychellois rupee, the Seychelles has Africa's highest GDP per capita.",
    "SDG": "Sudanese pound, Sudan split into two countries in 2011.",
    "SEK": "Swedish krona, Sweden is an EU member that voted to keep its own currency.",
    "SGD": "Singapore dollar, one of the world's most stable and valued currencies.",
    "SHP": "Saint Helena pound, used on the remote South Atlantic island of Saint Helena.",
    "SLL": "Sierra Leonean leone, Sierra Leone is a major diamond producer.",
    "SOS": "Somali shilling, Somalia has faced decades of civil conflict.",
    "SRD": "Surinamese dollar, Suriname is a small South American nation with gold reserves.",
    "STN": "São Tomé and Príncipe dobra, pegged to the euro via Portugal.",
    "SVC": "Salvadoran colón, El Salvador adopted Bitcoin as legal tender in 2021.",
    "SYP": "Syrian pound, has collapsed dramatically due to the ongoing civil war.",
    "SZL": "Swazi lilangeni, pegged 1:1 to the South African rand.",
    "THB": "Thai baht, Thailand is Southeast Asia's second-largest economy.",
    "TJS": "Tajikistani somoni, named after Ismoil Somoni, a Samanid ruler.",
    "TMT": "Turkmenistani manat, Turkmenistan has the world's fourth-largest gas reserves.",
    "TND": "Tunisian dinar, Tunisia is a major North African tourism destination.",
    "TOP": "Tongan paʻanga, Tonga is a Polynesian island kingdom in the Pacific.",
    "TRY": "Turkish lira, Turkey has faced high inflation in recent years.",
    "TTD": "Trinidad and Tobago dollar, T&T is a major Caribbean energy exporter.",
    "TWD": "New Taiwan dollar, Taiwan is the world's leading semiconductor manufacturer.",
    "TZS": "Tanzanian shilling, Tanzania hosts Kilimanjaro and the Serengeti.",
    "UAH": "Ukrainian hryvnia, Ukraine has faced significant economic strain since 2022.",
    "UGX": "Ugandan shilling, Uganda is a major coffee producer in Africa.",
    "USD": "US dollar, the world's primary reserve currency used in global trade.",
    "UYU": "Uruguayan peso, Uruguay is known for political stability in South America.",
    "UZS": "Uzbekistani som, Uzbekistan is a major cotton and gold producer.",
    "VES": "Venezuelan bolívar soberano, Venezuela has faced extreme hyperinflation.",
    "VND": "Vietnamese dong, Vietnam is one of Asia's fastest-growing economies.",
    "VUV": "Vanuatu vatu, Vanuatu is a Pacific archipelago of 80+ islands.",
    "WST": "Samoan tālā, Samoa is a small Polynesian island nation.",
    "XAF": "Central African CFA franc, shared by six Central African nations.",
    "XCD": "East Caribbean dollar, shared by eight Eastern Caribbean states.",
    "XOF": "West African CFA franc, shared by eight West African nations.",
    "XPF": "CFP franc, used in French Polynesia, New Caledonia, and Wallis and Futuna.",
    "YER": "Yemeni rial, Yemen has been in civil conflict since 2015.",
    "ZAR": "South African rand, the most traded African currency globally.",
    "ZMW": "Zambian kwacha, Zambia is one of Africa's largest copper producers.",
    "ZWL": "Zimbabwean dollar, Zimbabwe experienced one of history's worst hyperinflations.",
}

h = {"xc-token": API_KEY, "Content-Type": "application/json"}

# Fetch all records (id + Code + Notes)
resp = requests.get(
    f"{NOCODB_URL}/api/v1/db/data/noco/{BASE_ID}/{TABLE_ID}",
    headers=h,
    params={"fields": "Id,Code,Notes", "limit": 10000},
)
resp.raise_for_status()
rows = resp.json()["list"]
print(f"Fetched {len(rows)} records.")

updated = skipped = 0
for row in rows:
    code = row.get("Code", "")
    if row.get("Notes") or code not in NOTES:
        skipped += 1
        continue
    patch = requests.patch(
        f"{NOCODB_URL}/api/v1/db/data/noco/{BASE_ID}/{TABLE_ID}/{row['Id']}",
        headers=h,
        json={"Notes": NOTES[code]},
    )
    patch.raise_for_status()
    print(f"Updated: {code}")
    updated += 1

print(f"\nDone. Updated: {updated}, Skipped: {skipped}")
