/// @ts-check
const { ApolloServer } = require('@apollo/server');
const { expressMiddleware } = require('@as-integrations/express5');
const { ApolloServerPluginDrainHttpServer } = require('@apollo/server/plugin/drainHttpServer');
const { printSchema } = require('graphql');
const { buildSubgraphSchema } = require('@apollo/subgraph');
const Express = require("express");
const multer = require('multer');
const http = require('http');
const { typeDefs: scalarTypeDefs } = require('graphql-scalars');

// @ts-ignore
require('graphql-import-node/register');

const NocoDbClientFactory = require('./nocodb-client.factory');
const rabbitmqChannelFactory = require("./rabbitmq-channel.factory");

const { postFile } = require("./post-file.route");
const { getFile } = require("./get-file.route");
const { deleteFile } = require("./delete-file.route");
const { default: gql } = require('graphql-tag');

const fileResolver = require('./file.resolver');
const { ApolloServerPluginInlineTraceDisabled } = require('@apollo/server/plugin/disabled');

async function main() {
  let app = Express();
  let port = +(process.env.PORT || 80);
  let host = process.env.HOST || '0.0.0.0';

  const upload = multer()

  var nocoDbClient = await NocoDbClientFactory.generate();
  var rabbitChannel = await rabbitmqChannelFactory.generate();

  const DI = {
    nocoDbClient,
    rabbitChannel
  };

  const typeDefs = gql`
scalar DateTimeISO

type Query {
  files(input: FilesInput): FilesReponse!
}

extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.0"
    import: ["@key", "@shareable"]
  )

"""
File Entity to represent a file created on NocoDB
"""
type File @key(fields: "id") {
  """
  Unique ID for each file. It is generated by NocoDB.
  """
  id: ID!
  downloadPath: String
  mimeType: String!
  extension: String!
  fileName: String
  createdAt: DateTimeISO!
  updatedAt: DateTimeISO
  ocrID: ID
}

"""
Response type for files query which represents a list of files
"""
type FilesReponse {
  results: [File!]!
}

"""
Input type to filter files
"""
input FilesInput {
  ids: [ID!]
}
  `;

  const resolvers = {
    Query: {
      files(_, args) {
        const getFilePromises = args.input?.ids.map((id) => fileResolver.getFile(DI)({ id })) || [];
        const files = Promise.all(getFilePromises);

        return {
          results: files,
        }
      },
    },
    File: {
      __resolveReference(file, _) {
        return fileResolver.getFile(DI)(file);
      },
    },
  };

  const httpServer = http.createServer(app);

  // Set up Apollo Server
  const apolloServer = new ApolloServer({
    /// @ts-ignore
    schema: buildSubgraphSchema({ scalarTypeDefs, typeDefs, resolvers }),
    csrfPrevention: false,
    // typeDefs,
    // resolvers,
    plugins: [
      ApolloServerPluginDrainHttpServer({ httpServer }),
      ApolloServerPluginInlineTraceDisabled(),
      // ApolloServerPluginLandingPageDisabled()
      //  ApolloServerPluginLandingPageLocalDefault()
    ],
  });

  await apolloServer.start();

  app.use(
    '/graphql',
    Express.json(),
    /// @ts-ignore
    expressMiddleware(apolloServer),
  );

  /// @ts-ignore
  app.get('/', (_, res) => (res.send({ app: 'files-service' })))
  /// @ts-ignore
  app.post('/files', upload.single('file'), postFile(DI))
  /// @ts-ignore
  app.get('/files/:id', upload.single('file'), getFile(DI))
  /// @ts-ignore
  app.delete('/files/:id', upload.single('file'), deleteFile(DI))

  console.log(`App listening on port ${host}:${port}`)
  await new Promise((resolve) => httpServer.listen({ port, host, resolve }));
}

main().catch(console.error)
